# Generated by Django 3.1 on 2022-11-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cust',
        ),
    ]
