# Generated by Django 3.1 on 2022-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221126_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order Accepted', 'Order Accepted'), ('Order Completed', 'Order Completed'), ('Order Cancelled', 'Order Cancelled')], default='New', max_length=15),
        ),
    ]
